language: java
jdk: oraclejdk8
before_install:
- nvm install 4
- npm install
- npm install -g grunt-cli
script:
- ./gradlew build -x ktlint
- ./gradlew ktlint
- grunt test
after_success:
#  - ./gradlew dokka
- git clone -b gh-pages https://github.com/ThaumicMekanism/venus.git out && rm -rf out/.git
- test $TRAVIS_BRANCH = "master" && mv out/jvm jvm && rm -rf out && mkdir out && mv jvm out && grunt dist
- test $TRAVIS_BRANCH = "JVM" && rm -rf out/jvm && grunt distjvm
cache:
  directories:
  - node_modules/
deploy:
- provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: out
  keep-history: true
  on:
    branch: master
  email: deployer@travis-ci.org
  name: Travis CI Deployment

- provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: out
  keep-history: true
  on:
    branch: JVM
  email: deployer@travis-ci.org
  name: Travis CI Deployment

#  - provider: releases
#  github_token: $GITHUB_TOKEN
#  file_glob: true
#  file: build/libs/venus-*.jar
#  skip_cleanup: true
#  email: deployer@travis-ci.org
#  name: Travis CI Deployment
#  on:
#    tags: true
#    branch: