language: java
jdk: oraclejdk8
before_install:
  - npm install
script:
  - ./gradlew build -x ktlint
  - ./gradlew ktlint
  - grunt test
after_success:
  - grunt dist
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: out
  on:
    branch: master
